import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/provider/theme-provider";
import QueryClientTed from "@/client/query-client";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  ui_1,
}: Readonly<{
  children: React.ReactNode;
  ui_1: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientTed>
            {/* {children} */}
            {ui_1}
            <Toaster />
          </QueryClientTed>
        </ThemeProvider>
      </body>
    </html>
  );
}
